mysite/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>', views.add_cart, name='add_cart'),
    path('remove/<int:product_id>', views.cart_remove, name='cart_remove'),
    path('full_remove/<int:product_id>', views.full_remove, name='full_remove'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from mysite.views import HomeView
from mysite.views import HomeView, UserCreateView, UserCreateDoneTV


urlpatterns = [
    # 로그인, 로그아웃, 비밀번호 변경 등 담당
    path('accounts/', include('django.contrib.auth.urls')),
    # 회원 가입 및 처리
    path('accounts/register/', UserCreateView.as_view(), name='register'),
    path('accounts/register/done/',
         UserCreateDoneTV.as_view(), name='register_done'),
    path('', HomeView.as_view(), name='index'),

    path('admin/', admin.site.urls),
    path('product/', include('product.urls')),
    path('cart/', include('cart.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/product/urls.py
from django.urls import path
from product.views import *

app_name = 'product'

urlpatterns = [
    path('', ProductLV.as_view(), name='list'),
    path('<int:pk>/', ProductDV.as_view(), name='detail'),
    path('search/', SearchLView.as_view(), name='search'),
    # Example: /product/tag/
    path('tag/', TagCloudTV.as_view(), name='tag_cloud'),
    # Example: /product/tag/tagname/
    path('tag/<str:tag>/', TaggedObjectLV.as_view(), name='tagged_object_list'),
]

mysite/product/models.py
from django.db import models
from taggit.managers import TaggableManager

# Create your models here.


class Product(models.Model):
    name = models.CharField('NAME', max_length=50)
    cpu = models.CharField('CPU', max_length=50)
    ram = models.CharField('RAM', max_length=20)
    gpu = models.CharField('GPU', max_length=50)
    battery = models.CharField('BATTERY', max_length=20)
    volume = models.CharField('VOLUME', max_length=20)
    weight = models.DecimalField('WEIGHT', decimal_places=3, max_digits=4)
    display = models.DecimalField('DISPLAY', decimal_places=1, max_digits=3)
    maker = models.CharField('MAKER', max_length=50)
    sw_os = models.CharField('SW_OS', max_length=20, default='')
    price = models.IntegerField('PRICE')
    image = models.ImageField('IMAGE', blank=True)
    content = models.ImageField('CONTENT', blank=True)

    tags = TaggableManager(blank=True)

    def __str__(self):
        return self.name

    @property
    def imageURL(self):
        try:
            url = self.image.url
        except:
            url = ''

        return url


class Maker_list(models.Model):
    maker_list = models.CharField(verbose_name='MAKER_LIST', max_length=50)

    def __str__(self):
        return self.maker_list


class Cpu_list(models.Model):
    cpu_list = models.CharField(
        verbose_name='CPU_LIST', max_length=50, default='')

    def __str__(self):
        return self.cpu_list


class Ram_list(models.Model):
    ram_volume = models.CharField(
        verbose_name='RAM_VOLUME', max_length=20, default='')

    def __str__(self):
        return self.ram_volume


class Gpu_list(models.Model):
    gpu_list = models.CharField(
        verbose_name='GPU_LIST', max_length=50, default='')

    def __str__(self):
        return self.gpu_list


class Ssd_list(models.Model):
    ssd_volume = models.CharField(
        verbose_name='SSD_VOLUME', max_length=20, default='')

    def __str__(self):
        return self.ssd_volume


class Os_list(models.Model):
    os_list = models.CharField(
        verbose_name='OS_LIST', max_length=20, default='')

    def __str__(self):
        return self.os_list


class Display_list(models.Model):
    display_list = models.IntegerField(verbose_name='DISPLAY_LIST', default='')

    def __str__(self):
        return str(self.display_list)


class Weight_list(models.Model):
    weight_list = models.IntegerField(verbose_name='WEIGHT_LIST', default='')

    def __str__(self):
        return str(self.weight_list)

mysite/product/views.py
from django.shortcuts import render
from product.models import *
from django.views.generic import TemplateView, ListView, DetailView
from django.db.models import Q
from django.core.paginator import Paginator
from django.db.models import Count

# Create your views here.

# ListView


class ProductLV(ListView):
    model = Product
    template_name = 'product/product.html'  # 템플릿 파일명 변경 / 디폴트는 post_list
    context_object_name = 'products'  # 컨텍스트 객체 이름 변경 / 디폴트는 object_list
    paginate_by = 9  # 페이지네이션, 페이지 당 문서 건 수

    def get_queryset(self):

        products = Product.objects.all()

        sort = self.request.GET.get('sort', '')
        if sort == 'high_price':
            products = products.order_by('-price')
        elif sort == 'low_price':
            products = products.order_by('price')
        else:
            products = products.order_by('id')

        return products

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # 페이지네이션
        paginator = context['paginator']
        page_numbers_range = 5
        max_index = len(paginator.page_range)

        page = self.request.GET.get('page')
        current_page = int(self.request.GET.get('page', 1))

        start_index = int((current_page-1) /
                          page_numbers_range) * page_numbers_range
        end_index = start_index + page_numbers_range

        if end_index >= max_index:
            end_index = max_index

        page_range = paginator.page_range[start_index:end_index]
        context['page_range'] = page_range

        # 검색 필터 목록
        maker_list = Maker_list.objects.all()
        context['maker_list'] = maker_list
        # context['number_of_maker_list'] = maker_list.count()

        cpu_list = Cpu_list.objects.all()
        context['cpu_list'] = cpu_list
        # context['number_of_cpu_list'] = cpu_list.count()

        ram_list = Ram_list.objects.all()
        context['ram_list'] = ram_list
        # context['number_of_ram_list'] = ram_list.count()

        gpu_list = Gpu_list.objects.all()
        context['gpu_list'] = gpu_list
        # context['number_of_gpu_list'] = gpu_list.count()

        ssd_list = Ssd_list.objects.all()
        context['ssd_list'] = ssd_list
        # context['number_of_ssd_list'] = ssd_list.count()

        os_list = Os_list.objects.all()
        context['os_list'] = os_list
        # context['number_of_os_list'] = os_list.count()

        display_list = Display_list.objects.all()
        context['display_list'] = display_list
        # context['number_of_Display_list'] = display_list.count()

        weight_list = Weight_list.objects.all()
        context['weight_list'] = weight_list

        # 노트북 총 몇 건
        number_of_product = Product.objects.all().count()
        context['number_of_product'] = number_of_product

        sort = self.request.GET.get('sort', '')
        context['sort'] = sort

        return context

# DetailView


class ProductDV(DetailView):
    model = Product
    context_object_name = 'product'

# 검색 (클래스형)


class SearchLView(ListView):
    template_name = 'product/product_search.html'
    model = Product
    paginate_by = 9

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)  # context value들을 담는 컨테이너

        # 페이지네이션
        paginator = context['paginator']
        page_number_range = 5  # 페이지그룹에 속한 페이지 수
        current_page = int(self.request.GET.get('page', 1))

        # 시작/끝 index 조회
        start_index = int((current_page-1)/page_number_range)*page_number_range
        end_index = start_index + page_number_range

        # 현재 페이지가 속한 페이지 그룹의 범위
        current_page_group_range = paginator.page_range[start_index: end_index]

        start_page = paginator.page(current_page_group_range[0])
        end_page = paginator.page(current_page_group_range[-1])

        has_previous_page = start_page.has_previous()
        has_next_page = end_page.has_next()

        context['current_page_group_range'] = current_page_group_range
        if has_previous_page:  # 이전페이지 그룹이 있다면
            context['has_previous_page'] = has_previous_page
            context['previous_page'] = start_page.previous_page_number

        if has_next_page:  # 다음 페이지 그룹이 있다면
            context['has_next_page'] = has_next_page
            context['next_page'] = end_page.next_page_number

        # 검색 필터 목록
        maker_list = Maker_list.objects.all()
        context['maker_list'] = list(map(str, maker_list))
        # context['number_of_maker_list'] = maker_list.count()

        cpu_list = Cpu_list.objects.all()
        context['cpu_list'] = list(map(str, cpu_list))
        # context['number_of_cpu_list'] = cpu_list.count()

        ram_list = Ram_list.objects.all()
        context['ram_list'] = list(map(str, ram_list))
        # context['number_of_ram_list'] = ram_list.count()

        gpu_list = Gpu_list.objects.all()
        context['gpu_list'] = list(map(str, gpu_list))
        # context['number_of_gpu_list'] = gpu_list.count()

        ssd_list = Ssd_list.objects.all()
        context['ssd_list'] = list(map(str, ssd_list))
        # context['number_of_ssd_list'] = ssd_list.count()

        os_list = Os_list.objects.all()
        context['os_list'] = list(map(str, os_list))
        # context['number_of_os_list'] = os_list.count()

        display_list = Display_list.objects.all()
        context['display_list'] = list(map(str, display_list))
        # context['number_of_Display_list'] = display_list.count()

        weight_list = Weight_list.objects.all()
        context['weight_list'] = list(map(str, weight_list))
        # context['number_of_Display_list'] = display_list.count()

        # url 할당을 위한 변수
        get_full_path = self.request.get_full_path()

        if get_full_path.split('&')[-1].startswith('page'):
            get_full_path = ('&').join(get_full_path.split('&')[:-1])

        if get_full_path.split('?')[0] == get_full_path.split('?')[1]:
            get_full_path = get_full_path[34:]

        context['get_full_path'] = get_full_path

        # 체크박스 표시가 유지될 수 있도록 만든 context
        # Maker 체크박스 입력한 데이터 값들이 넘어옴(getlist -> 여러개 받을 수 있음)
        f_maker = self.request.GET.getlist('f_maker')
        context['f_maker_list'] = f_maker
        # CPU 체크박스 입력한 데이터 값들이 넘어옴(getlist -> 여러개 받을 수 있음)
        f_cpu = self.request.GET.getlist('f_cpu')
        context['f_cpu_list'] = f_cpu
        # RAM 체크박스 입력한 데이터 값들이 넘어옴(getlist -> 여러개 받을 수 있음)
        f_ram = self.request.GET.getlist('f_ram')
        context['f_ram_list'] = f_ram
        # GPU 체크박스 입력한 데이터 값들이 넘어옴(getlist -> 여러개 받을 수 있음)
        f_gpu = self.request.GET.getlist('f_gpu')
        context['f_gpu_list'] = f_gpu
        # SSD (volume) 체크박스 입력한 데이터 값들이 넘어옴(getlist -> 여러개 받을 수 있음) ---> 데이터 단위 조작 필요
        f_ssd = self.request.GET.getlist('f_ssd')
        context['f_ssd_list'] = f_ssd
        # SW_OS 체크박스 입력한 데이터 값들이 넘어옴(getlist -> 여러개 받을 수 있음)
        f_os = self.request.GET.getlist('f_os')
        context['f_os_list'] = f_os
        # DISPLAY 체크박스 입력한 데이터 값들이 넘어옴(getlist -> 여러개 받을 수 있음)
        f_display = self.request.GET.getlist('f_display')
        context['f_display_list'] = f_display
        # DISPLAY 체크박스 입력한 데이터 값들이 넘어옴(getlist -> 여러개 받을 수 있음)
        f_weight = self.request.GET.getlist('f_weight')
        context['f_weight_list'] = f_weight

        # 최소 가격 입력한 데이터 값들이 넘어옴(getlist -> 여러개 받을 수 있음)
        price_min = self.request.GET.get('price_min')
        context['price_min'] = price_min
        # 최대 가격 입력한 데이터 값들이 넘어옴(getlist -> 여러개 받을 수 있음)
        price_max = self.request.GET.get('price_max')
        context['price_max'] = price_max

        # 검색 결과 몇 건인지 나타내기 위한 context
        number_of_queryset = self.get_queryset().count()
        context['number_of_queryset'] = number_of_queryset

        sort = self.request.GET.get('sort', '')
        context['sort'] = sort

        return context

    def get_queryset(self):

        product_list = Product.objects.all()

        q = self.request.GET.get('q', '')  # 검색에서 입력한 값이 넘어옴

        # Maker 체크박스 입력한 데이터 값들이 넘어옴(getlist -> 여러개 받을 수 있음)
        f_maker = self.request.GET.getlist('f_maker')
        # CPU 체크박스 입력한 데이터 값들이 넘어옴(getlist -> 여러개 받을 수 있음)
        f_cpu = self.request.GET.getlist('f_cpu')
        # RAM 체크박스 입력한 데이터 값들이 넘어옴(getlist -> 여러개 받을 수 있음)
        f_ram = self.request.GET.getlist('f_ram')
        # GPU 체크박스 입력한 데이터 값들이 넘어옴(getlist -> 여러개 받을 수 있음)
        f_gpu = self.request.GET.getlist('f_gpu')
        # SSD (volume) 체크박스 입력한 데이터 값들이 넘어옴(getlist -> 여러개 받을 수 있음) ---> 데이터 단위 조작 필요
        f_ssd = self.request.GET.getlist('f_ssd')
        # SW_OS 체크박스 입력한 데이터 값들이 넘어옴(getlist -> 여러개 받을 수 있음)
        f_os = self.request.GET.getlist('f_os')
        # DISPLAY 체크박스 입력한 데이터 값들이 넘어옴(getlist -> 여러개 받을 수 있음)
        f_display = self.request.GET.getlist('f_display')
        # WEIGHT 체크박스 입력한 데이터 값들이 넘어옴(getlist -> 여러개 받을 수 있음)
        f_weight = self.request.GET.getlist('f_weight')

        price_min = self.request.GET.get('price_min', '')
        price_max = self.request.GET.get('price_max', '')

        if q:  # b(검색창)에서 값이 넘어왔다면
            product_list = product_list.filter(Q(name__icontains=q))

        if f_maker:  # f(체크박스 필터)에서 값이 넘어왔다면
            query = Q()
            for i in f_maker:
                query = (query | Q(maker__icontains=i))
            product_list = product_list.filter(query)

        if f_cpu:  # f(체크박스 필터)에서 값이 넘어왔다면
            query = Q()
            for i in f_cpu:
                query = (query | Q(cpu__icontains=i))
            product_list = product_list.filter(query)

        if f_ram:  # f(체크박스 필터)에서 값이 넘어왔다면
            query = Q()
            for i in f_ram:
                query = (query | Q(ram__icontains=i))
            product_list = product_list.filter(query)

        if f_gpu:  # f(체크박스 필터)에서 값이 넘어왔다면
            query = Q()
            for i in f_gpu:
                query = (query | Q(gpu__icontains=i))

mysite/product/templates/product/product_detail.html
{% extends "base.html" %}
{% load static %}
{% load humanize %}

{% block content %}
<!-- Breadcrumb End -->
<div class="breadcrumb-option set-bg" data-setbg="{% static 'img/notebookmain.jpg' %}">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <div class="breadcrumb__text">
                    <h2> {{ product.name }} </h2>
                    <div class="breadcrumb__links">
                        <a href="http://127.0.0.1:8000/">
                            <i class="fa fa-home"></i> Home </a>
                        <a href="{% url 'product:list' %}">Laptop Listing</a> <span> {{ product.name }} </span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Breadcrumb Begin -->

<!-- Car Details Section Begin -->
<section class="car-details spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-9">
                <div class="row">
                    <div class="col-sm-4"></div>
                    <!-- 제품 사진 -->
                    <div class="car__details__pic">
                        <!-- 메인 사진 -->
                        <div class="car__details__pic__large">
                            <img class="car-big-img" src="{{ product.imageURL }}" width="400px" alt="">
                        </div>
                    </div>

                </div>


                <!-- 정보 탭 -->
                <div class="car__details__tab">
                    <ul class="nav nav-tabs" role="tablist">
                        <li class="nav-item">
                            <a class="nav-link active" data-toggle="tab" href="#tabs-1" role="tab">Laptop Spec</a>

                    </ul>
                    <!-- 탭 별 내용 -->
                    <div class="tab-content">

                        <!-- 탭1 -->
                        <div class="tab-pane active" id="tabs-1" role="tabpanel">
                            <div class="car__details__tab__info">
                                <div class="row">
                                    <div class="col-lg-6 col-md-6">
                                        <div class="car__details__tab__info__item">
                                            <h5>General Information</h5>
                                            <ul>
                                                <li>
                                                    <i class="fa fa-check"></i>
                                                    제품명 : {{product.name}}
                                                </li>
                                                <li>
                                                    <i class="fa fa-check"></i>
                                                    CPU : {{product.cpu}}
                                                </li>
                                                <li>
                                                    <i class="fa fa-check"></i>
                                                    그래픽 : {{product.gpu}}
                                                </li>
                                                <li>
                                                    <i class="fa fa-check"></i>
                                                    RAM : {{product.ram}}GB
                                                </li>
                                                <li>
                                                    <i class="fa fa-check"></i>
                                                    저장장치 : SSD {{product.volume}}GB
                                                </li>
                                            </ul>
                                        </div>
                                    </div>
                                    <div class="col-lg-6 col-md-6">
                                        <div class="car__details__tab__info__item">
                                            <h5>General Information</h5>
                                            <ul>
                                                <li>
                                                    <i class="fa fa-check"></i>
                                                    제조사 : {{product.maker}}
                                                </li>
                                                <li>
                                                    <i class="fa fa-check"></i>
                                                    운영체제 : {{product.sw_os}}
                                                </li>
                                                <li>
                                                    <i class="fa fa-check"></i>
                                                    무게 : {{product.weight}}kg
                                                </li>
                                                <li>
                                                    <i class="fa fa-check"></i>
                                                    베터리 : {{product.battery}}Wh
                                                </li>
                                                <li>
                                                    <i class="fa fa-check"></i>
                                                    디스플레이 : {{product.display}}인치
                                                </li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div>
                                <b>TAGS</b>
                                <i class="fa fa-tag"></i>
                                {% load taggit_templatetags2_tags %}
                                {% get_tags_for_object object as "tags" %}
                                {% for tag in tags %}
                                <a href="{% url 'product:tagged_object_list' tag.name %}"> {{tag.name}}</a>
                                {% endfor %}

                            </div>
                            <div class="car__details__tab__feature">
                                <div class="row">
                                    <div class="col-lg-3 col-md-6 col-sm-6">
                                        <div class="car__details__tab__feature__item"></div>
                                    </div>
                                    <div class="col-lg-3 col-md-6 col-sm-6">
                                        <div class="car__details__tab__feature__item"></div>
                                    </div>
                                    <div class="col-lg-3 col-md-6 col-sm-6">
                                        <div class="car__details__tab__feature__item"></div>
                                    </div>
                                    <div class="col-lg-3 col-md-6 col-sm-6">
                                        <div class="car__details__tab__feature__item"></div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <!-- 탭2 -->
                        <div class="tab-pane" id="tabs-2" role="tabpanel">
                            <div class="car__details__tab__info">
                                <div class="row">
                                    <div class="col-lg-6 col-md-6">
                                        <div class="car__details__tab__info__item"></div>
                                    </div>
                                    <div class="col-lg-6 col-md-6">
                                        <div class="car__details__tab__info__item"></div>
                                    </div>
                                </div>
                            </div>
                            <div class="car__details__tab__feature">
                                <div class="row">
                                    <div class="col-lg-3 col-md-6 col-sm-6">
                                        <div class="car__details__tab__feature__item"></div>
                                    </div>
                                    <div class="col-lg-3 col-md-6 col-sm-6">
                                        <div class="car__details__tab__feature__item"></div>
                                    </div>
                                    <div class="col-lg-3 col-md-6 col-sm-6">
                                        <div class="car__details__tab__feature__item"></div>
                                    </div>
                                    <div class="col-lg-3 col-md-6 col-sm-6">
                                        <div class="car__details__tab__feature__item"></div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <!-- 탭3 -->
                        <div class="tab-pane" id="tabs-3" role="tabpanel">
                            <div class="car__details__tab__info">
                                <div class="row">
                                    <div class="col-lg-6 col-md-6">
                                        <div class="car__details__tab__info__item"></div>
                                    </div>
                                    <div class="col-lg-6 col-md-6">
                                        <div class="car__details__tab__info__item"></div>
                                    </div>
                                </div>
                            </div>
                            <div class="car__details__tab__feature">
                                <div class="row">
                                    <div class="col-lg-3 col-md-6 col-sm-6">
                                        <div class="car__details__tab__feature__item"></div>
                                    </div>
                                    <div class="col-lg-3 col-md-6 col-sm-6">
                                        <div class="car__details__tab__feature__item"></div>
                                    </div>
                                    <div class="col-lg-3 col-md-6 col-sm-6">
                                        <div class="car__details__tab__feature__item"></div>
                                    </div>
                                    <div class="col-lg-3 col-md-6 col-sm-6">
                                        <div class="car__details__tab__feature__item"></div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <!-- 탭4 -->
                        <div class="tab-pane" id="tabs-4" role="tabpanel">
                            <div class="car__details__tab__info">
                                <div class="row">
                                    <div class="col-lg-6 col-md-6">
                                        <div class="car__details__tab__info__item"></div>
                                    </div>
                                    <div class="col-lg-6 col-md-6">
                                        <div class="car__details__tab__info__item"></div>
                                    </div>
                                </div>
                            </div>
                            <div class="car__details__tab__feature">
                                <div class="row">
                                    <div class="col-lg-3 col-md-6 col-sm-6">
                                        <div class="car__details__tab__feature__item"></div>
                                    </div>
                                    <div class="col-lg-3 col-md-6 col-sm-6">
                                        <div class="car__details__tab__feature__item"></div>
                                    </div>
                                    <div class="col-lg-3 col-md-6 col-sm-6">
                                        <div class="car__details__tab__feature__item"></div>
                                    </div>
                                    <div class="col-lg-3 col-md-6 col-sm-6">
                                        <div class="car__details__tab__feature__item"></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <!-- 오른쪽 주문 정보 -->
            <div class="col-lg-3">
                <div class="car__details__sidebar">
                    <div class="car__details__sidebar__model">
                        <ul>
                            <li>Product name
                                <span> {{product.name}}</span>
                            </li>
                        </ul>

                    </div>
                    <div class="car__details__sidebar__payment">
                        <ul>
                            <li>Price
                                <span> {{product.price | intcomma}}원</span>
                            </li>
                        </ul>
                        <a href="#" class="primary-btn">
                            <i class="fa fa-credit-card"></i>
                            결제하기</a>
                        <a href="{% url 'cart:add_cart' product.id %}" class="primary-btn">
                            <i class="fa fa-cart-plus"></i>
                            장바구니</a>

                    </div>
                </div>
            </div>
        </div>
    </div>
</section><!-- Car Details Section End -->{% endblock %}